<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
     <OutputType>WinExe</OutputType>
	 <TargetFramework>net6.0</TargetFramework>
     <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
     <Nullable>enable</Nullable>
     <ImplicitUsings>enable</ImplicitUsings>
     <SelfContained>false</SelfContained>
     <UseAppHost>true</UseAppHost>
     <RollForward>LatestMajor</RollForward>
     <AssemblyTitle>SCA</AssemblyTitle>
     <RootNamespace>SCA</RootNamespace>
     <ApplicationIcon>assets\icone.ico</ApplicationIcon>
     <DefaultItemExcludes>$(DefaultItemExcludes);SCA.Core\**</DefaultItemExcludes>
     <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
 
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
     <Optimize>True</Optimize>
   </PropertyGroup>
 
   <ItemGroup>
     <PackageReference Include="Avalonia" Version="11.2.5" />
     <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.5" />
     <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
     <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.5" />
     <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
     <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
     <PackageReference Include="Avalonia.Diagnostics" Version="11.2.5" />
     <PackageReference Include="Material.Icons.Avalonia" Version="2.1.0" />
     <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.0-rc4.5" />
     <PackageReference Include="DotNetEnv" Version="3.1.1" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.32">
       <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
       <PrivateAssets>all</PrivateAssets>
     </PackageReference>
     <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.29" />
     <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.1" />
   </ItemGroup>
 
   <ItemGroup>
     <None Update=".env">
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
     </None>
     <AvaloniaResource Include="assets\**" />
     <None Update="runtimeconfig.template.json">
       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
     </None>
   </ItemGroup>
 
   <ItemGroup>
     <Content Include="assets\icone.ico" />
     <EmbeddedResource Include="..\docs\Manual do Usuário SCA v1.pdf" LogicalName="ManualSCA.pdf" />
   </ItemGroup>
 
   <ItemGroup>
     <ProjectReference Include="SCA.Core\SCA.Core.csproj" />
   </ItemGroup>

	<Target Name="OrganizeDLLs" AfterTargets="Build">
		<ItemGroup>
			<MyDlls Include="$(TargetDir)*.dll" Exclude="$(TargetDir)$(TargetName).dll" />
		</ItemGroup>
		<MakeDir Directories="$(TargetDir)dll" Condition="!Exists('$(TargetDir)dll')" />
		<Move SourceFiles="@(MyDlls)" DestinationFolder="$(TargetDir)dll" />
	</Target>
 
 </Project>
